# Generated by Django 3.1.1 on 2020-10-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0005_addtocarttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('houes_no', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(max_length=100, null=True)),
                ('city_state', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('mobile1', models.CharField(max_length=100, null=True)),
                ('mobile2', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out For Delivery', 'Out For Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True)),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
