# Generated by Django 3.1.1 on 2020-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20201012_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out For Delivery', 'Out For Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True),
        ),
    ]
