# Generated by Django 3.1.1 on 2020-10-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0008_auto_20201012_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order_product',
            name='payment_status',
            field=models.CharField(default='Not Done', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(blank=True, choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out For Delivery', 'Out For Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
