# Generated by Django 3.1.1 on 2020-10-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20201013_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='status',
        ),
        migrations.CreateModel(
            name='Order_product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('totalprice', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out For Delivery', 'Out For Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True)),
                ('order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.order_product')),
                ('pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
