# Generated by Django 3.1.1 on 2020-10-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20201014_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='orderdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_product_detail',
            name='expected_date',
            field=models.DateField(null=True),
        ),
    ]
