# Generated by Django 3.1.1 on 2020-10-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20201015_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
